
---


- hosts: envoy-servers
  remote_user: "{{user}}"
  gather_facts: true
  tasks:
  - name: build envoy workspace
    file:
      path: "{{item}}"
      state: directory
      mode: 0754
    with_items:
      - "{{envoy_workspace}}"
      - "{{envoy_workspace}}/bin"
      - "{{envoy_workspace}}/conf"
      - "{{envoy_workspace}}/lib64"
      - "{{envoy_workspace}}/logs"
      - "{{envoy_workspace}}/pb"
      - "{{envoy_workspace}}/benchmark"

  - name: upload envoy files
    synchronize:
      src: "{{item.src}}"
      dest: "{{item.dst}}"
      archive: true
      checksum: true
      compress: true
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=.cache"
        - "--exclude=logs"
        - "--exclude=*.pyc"
        - "--exclude=*~"
    with_items:
      - {"src": "../envoy/bin/envoy", "dst": "{{envoy_workspace}}/bin/envoy"}
      - {"src": "../envoy/bin/envoyd.sh", "dst": "{{envoy_workspace}}/bin/envoyd.sh"}
      - {"src": "../envoy/bin/start_envoy.sh", "dst": "{{envoy_workspace}}/bin/start_envoy.sh"}
      - {"src": "../envoy/bin/hot-restarter.py", "dst": "{{envoy_workspace}}/bin/hot-restarter.py"}
      - {"src": "../envoy/conf/server.json", "dst": "{{envoy_workspace}}/conf/server.json"}
      - {"src": "../benchmark/helloworld_pb2.py", "dst": "{{envoy_workspace}}/benchmark/helloworld_pb2.py"}
      - {"src": "../benchmark/helloworld_pb2_grpc.py", "dst": "{{envoy_workspace}}/benchmark/helloworld_pb2_grpc.py"}
      - {"src": "../benchmark/benchmark_grpc_server.sh", "dst": "{{envoy_workspace}}/benchmark/benchmark_grpc_server.sh"}
      - {"src": "../benchmark/greeter_server.py", "dst": "{{envoy_workspace}}/benchmark/greeter_server.py"}
      - {"src": "../benchmark/start_benchmark_server.sh", "dst": "{{envoy_workspace}}/benchmark/start_benchmark_server.sh"}

  - name: upload library
    synchronize:
      src: "{{item.src}}"
      dest: "{{item.dst}}"
      archive: true
      checksum: true
      compress: true
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=.cache"
        - "--exclude=logs"
        - "--exclude=*.pyc"
        - "--exclude=*~"
    with_items:
      - {"src": "../envoy/lib64/libstdc++.so.6", "dst": "{{envoy_workspace}}/lib64/libstdc++.so.6"}
    when: skip_libs is undefined

  - name: install monit on centos
    become: true
    yum:
      name: monit
      state: latest

    when: ansible_os_family == "CentOS"

  - name: install monit on debian
    become: true
    apt:
      name: monit
      state: latest

    when: ansible_os_family == "Debian"

  - name: start monit service
    service:
      name: monit
      state: started

  - name: compile envoy configuration
    become: true
    template:
      src: "envoy.conf.j2"
      dest: "{% if ansible_os_family == \"Debian\" %}/etc/monit/conf-enabled{% else %}/etc/monit.d{% endif %}/envoy.conf"
    notify: reload monit

  handlers:
  - name: reload monit service
    listen: reload monit
    service:
      name: monit
      state: reloaded
